### ISSUE TITLE
Privacy notice should be scrollable

### ISSUE THREAD

**Issue by koppor** [InAnYan/jabref#125]
If JabRef is used in a small screen resolution, I cannot reach the "Agree" button without resizing the entry editor:

![image](https://github.com/user-attachments/assets/7fb216db-65e5-42e0-8a70-0d7f291c1457)

Other components to have a scroll bar:

![image](https://github.com/user-attachments/assets/628c8a9b-ba34-4afb-9289-caa1c7377125)

**Comment by InAnYan** [comment]
I made it scrollable, but should it be horizontally scrollable?

Should the text wrap or not?

**Comment by koppor** [comment]
> I made it scrollable, but should it be horizontally scrollable?

No.

> Should the text wrap or not?

Yes.

---

For basic UX design, try to think what end users applications do. A web browser is a good example.

In this case, a very basic text-based page is enough. If one opens https://blog.fefe.de/ in a browser, there is only a vertical scroll bar, no horiziontal scrollbar. --> it got common in browsers to do soft wrapping, and vertical scrolling.

**Comment by InAnYan** [comment]
Fixed partially.

Blocked by https://bugs.openjdk.org/browse/JDK-8090400

**Comment by koppor** [comment]
We cannot do HTML / WebView here?

---

Please do not close issues as completed if they are not solved. The label "depends-on-external" are made for issues like that.

**Comment by InAnYan** [comment]
Oh, we can. Though I wonder how to listen to button clicks. Should that be done today?

**Comment by koppor** [comment]
> Oh, we can. Though I wonder how to listen to button clicks. Should that be done today?

No. Week 12 :)

For now, it is good enough 😅
